EXP:
    ID: lhg
    OUTPUT_DIR: data

DATASET:
    NAME: lhq
    ROOT: LHQ/lhq_256_jpg #/home/kmuvcl09/h/LHQ/lhq_256_jpg_s
    LABELS:
    SPLIT:
        TRAIN:
        VAL:
        TEST:
    N_CLASSES: 182
    IGNORE_LABEL: 255
    SCALES: [0.5, 0.75, 1.0, 1.25, 1.5]


DATALOADER:
    NUM_WORKERS: 0

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        BASE: 1024
        TRAIN: 321
        TEST: 513

MODEL:
    NAME: DeepLabV2_ResNet101_MSC
    N_BLOCKS: [3, 4, 23, 3]
    ATROUS_RATES: [6, 12, 18, 24]
    INIT_MODEL: data/models/coco/deeplabv2_resnet/deeplabv2_resnet101_msc-cocostuff164k-100000.pth


CRF:
    ITER_MAX: 10
    POS_W: 10
    POS_XY_STD: 3
    BI_W: 4
    BI_XY_STD: 67
    BI_RGB_STD: 3